<?xml version="1.0" encoding="UTF-8"?><record_update sys_domain="global" table="sys_ui_application">
    <sys_ui_application action="INSERT_OR_UPDATE">
        <active>true</active>
        <hint/>
        <name>Exception management</name>
        <order/>
        <roles>x_454869_exception.exceptions_user</roles>
        <sys_class_name>sys_ui_application</sys_class_name>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2020-03-29 19:17:50</sys_created_on>
        <sys_domain>global</sys_domain>
        <sys_domain_path>/</sys_domain_path>
        <sys_id>feb6f46adbfb4010f3402706ca961988</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>Exception management</sys_name>
        <sys_overrides/>
        <sys_package display_value="Exception management" source="x_454869_exception">37d5f8e6dbfb4010f3402706ca9619f2</sys_package>
        <sys_policy/>
        <sys_scope display_value="Exception management">37d5f8e6dbfb4010f3402706ca9619f2</sys_scope>
        <sys_update_name>sys_ui_application_feb6f46adbfb4010f3402706ca961988</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2020-03-29 19:17:50</sys_updated_on>
    </sys_ui_application>
</record_update>
